# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
          -  main 
  pull_request:
    branches:
          -  main 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
     - name: List available Xcode versions
       run: ls /Applications | grep Xcode

     # Runs a single command using the runners shell
     - name: Run a one-line script
       run: sudo xcode-select -switch /Applications/Xcode_12.2.app && /usr/bin/xcodebuild -version
     - name: Install Dependencies
       run: |
         pod install --repo-update

     # Runs a set of commands using the runners shell
     - name: Run a multi-line script
       run: |
          xcodebuild test -workspace GameCenter2.xcworkspace -scheme GameCenter2 -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=14.2"
