name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: /usr/bin/xcodebuild test -workspace "GameCenter2.xcworkspace" -scheme "GameCenter2" -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'

